language: php
php:
    - '5.3'
script:
    - vendor/bin/phpunit --bootstrap garp/tests/TestHelper.php tests/
before_script:
    - chmod -R +x vendor
    #- ln -nfs BlackHole.php library/Zend/Cache/Backend/Blackhole.php
notifications:
    email: false
    slack:
        rooms:
            - secure: U98DgZzKManIEHvyV09gHzBwuEZqPLCBmtu4VZgs+783/xeq4sIkZEV+zmVw4chs75RTnanEqEpYT/tZCsVqx6NFSoyMUI8dl5dTmdyKlKtDhdeIjizlc+lM29OaqoJAFpcN1GtBASzYXT51qrBIql1Pyp4OFujHP27dfFPC2e0=
        on_success: change
        on_failure: always
        template: "<%{build_url}|%{repository_name} [%{branch}] #%{build_number}>:\n%{message} (in %{duration})\nBy: %{author}\n<%{compare_url}|%{commit_message}>"
