language: php
php:
    - '5.3'
script:
    - echo ${TRAVIS_BUILD_DIR}
    - vendor/bin/phpunit --include-path "${TRAVIS_BUILD_DIR}/library" --bootstrap garp/tests/TestHelper.php tests/
before_script:
    - chmod -R +x vendor
    - ln -nfs library/Zend/Cache/Backend/BlackHole.php library/Zend/Cache/Backend/Blackhole.php
notifications:
    email: false
    slack:
        secure: h9R+NUBeVXZfJ37cbdX72/ICIYS8mXMS2WR8DGDsTCx+mT6cru+D1UvnorXpOcPkv8FdX6aDHfK8LjsAT1a3IgcImRwVW4kdC7hq4L/NNlNNnTTchE/5+N6JqNY9nxrNweivMu/yuG/UzMVPLu5F1pyP3D26WGBelS3Y4eV+SgU=
